services:
  alpine-client:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - guacnetwork
    ports:
      - "5900:5900"
      - "2234-2239:2234-2239"  # Default Nicotine+ ports

  guacd:
    image: lscr.io/linuxserver/guacd:latest
    networks:
      - guacnetwork

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: guacamole
      POSTGRES_PASSWORD: guacamole_password
      POSTGRES_DB: guacamole_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - guacnetwork
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U guacamole"]
      interval: 10s
      timeout: 5s
      retries: 5
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    ports:
      - "5050:80"
    networks:
      - guacnetwork
    depends_on:
      - postgres

  init-guacamole-db:
    build:
      context: ./init
      dockerfile: Dockerfile
    environment:
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole
      POSTGRES_PASSWORD: guacamole_password
    networks:
      - guacnetwork
    depends_on:
      postgres:
        condition: service_healthy

  guacamole:
    image: guacamole/guacamole
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRESQL_HOSTNAME: postgres
      POSTGRESQL_DATABASE: guacamole_db
      POSTGRESQL_USER: guacamole
      POSTGRESQL_PASSWORD: guacamole_password
    depends_on:
      postgres:
        condition: service_healthy
      guacd:
        condition: service_started
      init-guacamole-db:
        condition: service_completed_successfully
    networks:
      - guacnetwork
    ports:
      - "8080:8080"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - guacamole
    networks:
      - guacnetwork

networks:
  guacnetwork:

volumes:
  postgres-data:
  guacamole_config:

