version: '3'

services:
  guacd:
    image: guacamole/guacd
    networks:
      - guacnetwork

  guacamole:
    image: guacamole/guacamole
    networks:
      - guacnetwork
    environment:
      GUACD_HOSTNAME: guacd
      POSTGRES_HOSTNAME: postgres
      POSTGRES_DATABASE: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_pass
      GUACAMOLE_HOME: /config/guacamole
    depends_on:
      - guacd
      - postgres
    ports:
      - "8080:8080"
    volumes:
      - guacamole_config:/config/guacamole
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    image: postgres:13
    networks:
      - guacnetwork
    environment:
      POSTGRES_DB: guacamole_db
      POSTGRES_USER: guacamole_user
      POSTGRES_PASSWORD: guacamole_pass
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./initdb.sql:/docker-entrypoint-initdb.d/initdb.sql

  nginx:
    image: nginx:alpine
    networks:
      - guacnetwork
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      guacamole:
        condition: service_healthy

  alpine-client:
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - guacnetwork
    ports:
      - "5900:5900"
      - "2234-2239:2234-2239"  # Default Nicotine+ ports

networks:
  guacnetwork:

volumes:
  postgres-data:
  guacamole_config:
